# https://taskfile.dev

version: '3'

vars:
  GOK_NAME: hello

tasks:

  gok_add:
    cmds:
      - gok add -i {{.GOK_NAME}} github.com/drummonds/gophoto
      # - gok add -i {{.GOK_NAME}} /home/hum3/minor_projects/gophoto

  update:
    cmds:
      - CGO_ENABLED=0 GOARCH=arm64 gok -i {{.GOK_NAME}} update

  local:
    cmds:
      - go run .

  build:
    cmds:
      - CGO_ENABLED=0 GOARCH=arm64 gok -i hello overwrite --full x.img --target_storage_bytes=1258299392
